version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: andrerodri13/php-8
    working_dir: /var/www
    volumes:
      - ./:/var/www #origem:destino -> local:container
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80 #localhost:container
#      - 445:443 #localhost:container -> porta SSL
    volumes:
      - ./:/var/www #mapeia diretorio local : workdir container
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
   app-php:
     driver: bridge

